=== CTrabant/StationJSON/fdsn-station-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "required": [ "schemaVersion", "networks" ],
    "additionalProperties": false,
    "properties": {
        "schemaVersion": {
            "type": "string",
            "description": "Version of schema this document conforms to"
        },
        "created": {
            "$ref": "#/definitions/fdsn-date-time"
        },
        "module": {
            "type": "string",
            "description": "Name of the software module that generated this document"
        },
        "moduleURI": {
            "type": "string",
            "description": "URI of the request that generated this document"
        },
        "sender": {
            "type": "string",
            "description": "Name of the institution sending this message"
        },
        "source": {
            "type": "string",
            "description": "Network ID of the institution sending the message"
        },
        "networks": {
            "type": "array",
            "items": { "$ref": "#/definitions/network" }
        }
    },
    "definitions": {
        "fdsn-date-time": {
            "type": [ "string", "null" ],
            "format": "date-time",
            "description": "Date and time in one form of ISO 8601, specifically YYYY-MM-DDThh:mm:ss[.SSSSSS]"
        },
        "fdsn-latitude": {
            "type": "number",
            "minimum": -90,
            "maximum": 90,
            "description": "geographic coordinate in WGS84 datum (degrees)"
        },
        "fdsn-longitude": {
            "type": "number",
            "minimum": -180,
            "maximum": 180,
            "description": "geographic coordinate in WGS84 datum (degrees)"
        },
        "fdsn-elevation": {
            "type": "number",
            "description": "elevation relative to WGS84 datum (meters)"
        },
        "fdsn-restrictedStatus": {
            "enum": [ "open", "closed", "partial" ],
            "description": "Data access restriction status"
        },
        "fdsn-timeSpan": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "start": {
                    "$ref": "#/definitions/fdsn-date-time"
                },
                "end": {
                    "$ref": "#/definitions/fdsn-date-time"
                }
            }
        },
        "fdsn-dataSpan": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "time": {
                        "$ref": "#/definitions/fdsn-timeSpan",
                        "description": "Time range of span"
                    },
                    "numberSegments": {
                        "type": "integer",
                        "description": "Number of contiguous time series segments in span"
                    },
                    "maximumTimeTear": {
                        "type": "number",
                        "description": "Maximum time tear, gap or overlap, between segments (seconds)"
                    }
                }
            }
        },
        "fdsn-responseStage": {
            "type": "object",
            "properties": {
                "poleszeros": {
                    "$ref": "#/definitions/fdsn-poleszeros"
                },
                "coefficients": {
                    "$ref": "#/definitions/fdsn-coefficients"
                },
                "responseList": {
                    "$ref": "#/definitions/fdsn-responseList"
                },
                "fir": {
                    "$ref": "#/definitions/fdsn-fir"
                },
                "decimation": {
                    "$ref": "#/definitions/fdsn-poleszeros"
                },
                "stageGain": {
                    "$ref": "#/definitions/fdsn-poleszeros"
                },
                "polynomial": {
                    "$ref": "#/definitions/fdsn-polynomial"
                }
            },
            "oneOf": [
                { "required": ["poleszeros", "stageGain"] },
                { "required": ["coefficients", "stageGain"] },
                { "required": ["responseList", "stageGain"] },
                { "required": ["fir", "stageGain"] },
                { "required": ["poleszeros", "decimation", "stageGain"] },
                { "required": ["coefficients", "decimation", "stageGain"] },
                { "required": ["responseList", "decimation", "stageGain"] },
                { "required": ["fir", "decimation", "stageGain"] },
                { "required": ["polynomial"] }
            ],
            "additionalProperties": false
        },
        "fdsn-baseFilter": {
            "type": "object",
            "properties": {
                "name": { "type": "string"},
                "description": { "type": "string"},
                "inputUnits": { "$ref": "#/definitions/fdsn-units" },
                "outputUnits": { "$ref": "#/definitions/fdsn-units" }
            }
        },
        "fdsn-units": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": { "type": "string"},
                "description": { "type": "string"}
            }
        },
        "fdsn-poleszeros": {
            "type": "object",
            "additionalProperties": false,
                "allOf": [
                    { "$ref": "#/definitions/fdsn-baseFilter" },
                    { "properties": {
                            "pzTransferFunctionType": {
                                "type": "string",
                                "enum": [ "LAPLACE (RADIANS/SECOND)", "LAPLACE (HERTZ)", "DIGITAL (Z-TRANSFORM)" ]
                            },
                            "normalizationFactor": {
                                "type": "number"
                            },
                            "normalizationFrequency": {
                                "type": "number"
                            },
                            "zero": {
                                "type": "array",
                                "items": {
                                    "type": { "$ref": "#/definitions/fdsn-floatNoUnit" }
                                }
                            },
                            "pole": {
                                "type": "array",
                                "items": {
                                    "type": { "$ref": "#/definitions/fdsn-floatNoUnit" }
                                }
                            }
                        }
                    }
                ]
        },
        "fdsn-fir": {
            "type": "object",
            "additionalProperties": false,
                "allOf": [
                    { "$ref": "#/definitions/fdsn-baseFilter" },
                    { "properties": {
                            "symmetry": {
                                "type": "string",
                                "enum": [ "NONE", "EVEN", "ODD" ]
                            },
                            "numeratorCoefficient": {
                                "type": "array",
                                "items": { "$ref": "#/definitions/fdsn-floatNoUnit" }
                            }
                        }
                    }
                ]
        },
        "fdsn-coefficients": {
            "type": "object",
            "additionalProperties": false,
                "allOf": [
                    { "$ref": "#/definitions/fdsn-baseFilter" },
                    { "properties": {
                            "cfTransferFunctionType": {
                                "type": "string",
                                "enum": [ "ANALOG (RADIANS/SECOND)", "ANALOG (HERTZ)", "DIGITAL" ]
                            },
                            "numeratorCoefficient": {
                                "type": "array",
                                "items": { "$ref": "#/definitions/fdsn-floatNoUnit" }
                            },
                            "denominatorCoefficient": {
                                "type": "array",
                                "items": { "$ref": "#/definitions/fdsn-floatNoUnit" }
                            }
                        }
                    }
                ]
        },
        "fdsn-responseList": {
            "type": "object",
            "additionalProperties": false,
                "allOf": [
                    { "$ref": "#/definitions/fdsn-baseFilter" },
                    { "properties": {
                            "responseListElement": {
                                "type": "array",
                                "items": { "$ref": "#/definitions/fdsn-responseListElement" }
                            }

                        }
                    }
                ]
        },
        "fdsn-decimation": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "inputSampleRate": {"type": "number"},
                "factor": {"type": "number"},
                "offset": {"type": "number"},
                "delay": {"type": "number"},
                "correction": {"type": "number"}
            }
        },
        "fdsn-stageGain": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "value": {"type": "number"},
                "frequency": {"type": "number"}
            }
        },
        "fdsn-polynomial": {
            "type": "object",
            "additionalProperties": false,
                "allOf": [
                    { "$ref": "#/definitions/fdsn-baseFilter" },
                    { "properties": {
                            "approximationType": {
                                "type": "string",
                                "enum": [ "MACLAURIN" ]
                            },
                            "frequencyLowerBound": {"type": "number"},
                            "frequencyUpperBound": {"type": "number"},
                            "approximationLowerBound": {"type": "number"},
                            "approximationUpperBound": {"type": "number"},
                            "maximumError": {"type": "number"},
                            "coefficient": {
                                "type": "array",
                                "items": { "$ref": "#/definitions/fdsn-floatNoUnit" }
                            }
                        }
                    }
                ]
        },
        "fdsn-floatNoUnit": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "value": {"type": "number"},
                "plusError": {"type": "number"},
                "minusError": {"type": "number"}
            }
        },
        "fdsn-responseListElement": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
               "frequency": {"type": "number"},
               "amplitude": {"type": "number"},
               "phase": {"type": "number"}
            }
        },
        "networkAttr": {
            "type": "object",
            "required": [ "code", "startTime", "endTime", "description" ],
            "properties": {
                "code": {
                    "type": "string",
                    "description": "FDSN SEED network code"
                },
                "startTime": {
                    "$ref": "#/definitions/fdsn-date-time"
                },
                "endTime": {
                    "$ref": "#/definitions/fdsn-date-time"
                },
                "description": {
                    "type": "string",
                    "description": "Description of network operator"
                },
                "restrictedStatus": {
                    "$ref": "#/definitions/fdsn-restrictedStatus"
                },
                "totalNumberStations": {
                    "type": "integer",
                    "description": "Total number of stations at sending data center"
                },
                "selectedNumberStations": {
                    "type": "integer",
                    "description": "Selected number of stations"
                },
                "dataAvailability": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "extent": {
                            "$ref": "#/definitions/fdsn-timeSpan",
                            "description": "Earliest and latest data time"
                        }
                    },
                    "description": "Description of network data availablity"
                }
            }
        },
        "network": {
            "allOf": [
                { "$ref": "#/definitions/networkAttr" },
                {
                  "properties": {
                    "stations": {
                        "type": "array",
                        "items": { "$ref": "#/definitions/station" }

                     }
                   }
                 }
             ]
        },
        "stationAttr": {
            "type": "object",
            "required": [ "code", "startTime", "latitude", "longitude", "elevation", "site" ],
            "properties": {
                "code": {
                    "type": "string",
                    "description": "FDSN SEED station code"
                },
                "startTime": {
                    "$ref": "#/definitions/fdsn-date-time"
                },
                "endTime": {
                    "$ref": "#/definitions/fdsn-date-time"
                },
                "latitude": {
                    "$ref": "#/definitions/fdsn-latitude"
                },
                "longitude": {
                    "$ref": "#/definitions/fdsn-longitude"
                },
                "elevation": {
                    "$ref": "#/definitions/fdsn-elevation"
                },
                "site": {
                    "type": "object",
                    "required": [ "name" ],
                    "additionalProperties": false,
                    "properties": {
                        "name": {
                            "type": "string",
                            "description": "Short site location description"
                        },
                        "description": {
                            "type": "string",
                            "description": "Longer description of the site location"
                        }
                    }
                },
                "restrictedStatus": {
                    "$ref": "#/definitions/fdsn-restrictedStatus"
                },
                "totalNumberChannels": {
                    "type": "integer",
                    "description": "Total number of channels at sending data center"
                },
                "selectedNumberChannels": {
                    "type": "integer",
                    "description": "Selected number of channels"
                },
                "dataAvailability": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "extent": {
                            "$ref": "#/definitions/fdsn-timeSpan",
                            "description": "Earliest and latest data time"
                        }
                    },
                    "description": "Description of station data availablity"
                }
            }
        },
        "station": {
            "allOf": [
                { "$ref": "#/definitions/stationAttr" },
                {
                  "properties": {
                    "channels": {
                        "type": "array",
                        "items": { "$ref": "#/definitions/channelAttr" }
                     }
                   }
                 }
             ]
        },
        "channelAttr": {
            "type": "object",
            "required": [ "location", "code", "startTime", "endTime", "latitude", "longitude", "elevation", "sampleRate", "sensorDescription" ],
            "properties": {
                "location": {
                    "type": "string",
                    "description": "FDSN SEED location identifer"
                },
                "code": {
                    "type": "string",
                    "description": "FDSN SEED channel codes"
                },
                "startTime": {
                    "$ref": "#/definitions/fdsn-date-time"
                },
                "endTime": {
                    "$ref": "#/definitions/fdsn-date-time"
                },
                "latitude": {
                    "$ref": "#/definitions/fdsn-latitude"
                },
                "longitude": {
                    "$ref": "#/definitions/fdsn-longitude"
                },
                "elevation": {
                    "$ref": "#/definitions/fdsn-elevation"
                },
                "depth": {
                    "type": "number",
                    "description": "Local depth or overburden (meters)"
                },
                "azimuth": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 360,
                    "description": "Channel azimuth (degrees from north, clockwise)"
                },
                "dip": {
                    "type": "number",
                    "minimum": -90,
                    "maximum": 90,
                    "description": "Channel dip (degrees down from horizontal)"
                },
                "sensorDescription": {
                    "type": "string",
                    "description": "Short description of instrument"
                },
                "sampleRate": {
                    "type": "number",
                    "description": "Channel sample rate (Hertz)"
                },
                "scale": {
                    "type": "number",
                    "description": "A divisor for converting to Earth units"
                },
                "scaleUnits": {
                    "type": "string",
                    "description": "Resulting units when dividing by scale"
                },
                "scaleFrequency": {
                    "type": "number",
                    "description": "Frequency in Hertz at which scale is valid"
                },
                "restrictedStatus": {
                    "$ref": "#/definitions/fdsn-restrictedStatus"
                },
                "dataAvailability": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "extent": {
                            "$ref": "#/definitions/fdsn-timeSpan",
                            "description": "Earliest and latest data time"
                        },
                        "span": {
                            "$ref": "#/definitions/fdsn-dataSpan",
                            "description": "Earliest and latest data time"
                        }
                    },
                    "description": "Description of channel data availablity"
                }
            }
        }
    }
}

=== CTrabant/StationJSON/example-fdsn-station-STATION.json
{
    "schemaVersion": "1.0",
    "created": "2014-11-19T17:50:38Z",
    "module": "IRIS WEB SERVICE: fdsnws-station | version: 1.0.0-TEST",
    "moduleURI": "http://service.iris.edu/fdsnws/station/1/query?net=IU&sta=ANMO&level=station&format=json",
    "sender": "IRIS-DMC",
    "source": "IRIS-DMC",
    "networks": [
        {
            "code": "IU",
            "startTime": "2000-01-01T11:30:22Z",
            "endTime": "2599-12-31T23:59:59Z",
            "description": "Global Seismograph Network (GSN - IRIS/USGS)",
            "restrictedStatus": "open",
            "totalNumberStations": 92,
            "selectedNumberStations": 1,
            "stations": [
                {
                    "code": "ANMO",
                    "startTime": "2000-01-01T11:30:22Z",
                    "endTime": "2003-01-01T11:30:22Z",
                    "latitude": 34.9502,
                    "longitude": -106.4602,
                    "elevation": 1839.0,
                    "site": {
                        "name": "Albuquerque, New Mexico, USA",
                        "description": "Near the edge of the base outside of Alburquerque"
                    },
                    "restrictedStatus": "open",
                    "totalNumberChannels": 50,
                    "selectedNumberChannels": 50
                }
            ]
        }
    ]
}
